### PR TITLE
[DX-1156] fix: Undecimalise amounts on deposits

### PR DESCRIPTION
**Pull request by CodeSchwert**
# Summary

https://immutable.atlassian.net/browse/DX-1156

Update deposit workflows to accept undecimalised amounts to match the behaviour of APIs (and industry norms).

# Why the changes

One of the Core SDK TS version 1 proposals: https://immutable.atlassian.net/wiki/spaces/PPS/pages/1950944070/TS+Core+SDK+interface+proposal 

# Things worth calling out

- Tested transfers workflow to make sure that also used undecimalised amounts, which it does.

### CODE REVIEW

**Review by zatlite — APPROVED** [review]
LGTM

**Comment by Kastet** [comment]
Nice one!
Question - all other workflows and APIs already work with undecimalised amounts?

@zatlite @CodeSchwert Aung is working on improving the interface of token params, now that we're opinionated about the amount format how about we make it more explicit in the interface, e.g. `undecimalizedAmount` (or some other term) instead of `amount`? Or at the very least add comments.

**Review by Kastet — APPROVED** [review]

**Comment by CodeSchwert** [comment]
> Nice one! Question - all other workflows and APIs already work with undecimalised amounts?
> 
> @zatlite @CodeSchwert Aung is working on improving the interface of token params, now that we're opinionated about the amount format how about we make it more explicit in the interface, e.g. `undecimalizedAmount` (or some other term) instead of `amount`? Or at the very least add comments.

@Kastet All workflows should work with undecimalised amounts (unless I missed one).

Looks like we could update the interfaces for deposits pretty easily to `undecimalizedAmount`:
- https://github.com/immutable/imx-core-sdk/blob/8a91985ea142685ebed352c1f14da3021a6de7ff/src/types/deposit.ts#L5
- https://github.com/immutable/imx-core-sdk/blob/8a91985ea142685ebed352c1f14da3021a6de7ff/src/types/deposit.ts#L12

Changing it for transfer looks a bit trickier since the interface is basically the auto-generated one.

**Comment by Kastet** [comment]
@CodeSchwert https://github.com/immutable/imx-core-sdk/pull/149 is merged

**Pull request merged**
